language: java

jdk:
  - oraclejdk8

script: ./gradlew build

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "ISWZj7fGXG/IWS3HdlAe22cTn7SyPahp+lKimPoZlJH8rx7akAKA59rtcvgpSVOkfVzzGDh+pUkne8iVRzZsDYLYsDQ/ihlhjX3i9FU8msZXIV6VgUXG75UpzjoqTkt1hQ4uqC0sVWYnpJEC7tU/RG7h/lSkqIwY19Um5r4R/CFsm4SJq8TeEA8XuVrUNi0oEzYc4YjuxKhAMHyX/8njnLP7wkDthO9dRu0JHadYYi6tsbEiSv3ozrP5dSuD6MzKS/X5hL8UKhQKl5OHgtmuKXYRAMF+3WOWVMPdoOmP1WkycDn6Txsd9WuZSRZC/JdgHLFA8m2RpkAfqGVLo+tMAqOvf06o1BsBWkFgjwFM0Z4gD9rDbPSVkyiI4YCWGVMZ7f9EvpZsQysjw4dAYH92uL1ySvAXNqp2a1PqxO2364XzeAEG/66bM178XeNgpjcye/v+0EKxZxFM9xORFrPtyBsiJnFp6+jOFT3CI5u+wFuYpRekNhOk2WaeuMQ8ccYEi8R8ZCy/EWqEIGcTKfdG/skButtyg9IJtPhIg32283imcK3CGP5SDUQbKj0MHffpRVNUaHMlobcoRkpcPPLZJjowoWtfAhjQ7IBCeUlSoGT0dYpa1PGSmkmPMeKM66Spf5I+xETwBop3b5fqEM5k4iiLi5AcwUq3AewAPUFDUA0="
    - secure: "M8LCUcYX52PuoUK4JV63jQHnHhr9enPbvJmgMmcZdvCrNb9n0ib7EQ/BOL5ooLIMD3i1M1pmmACa7AyftcSOsNA2S+fPnv9Vjn8s1w1r8JefRwnBWSLhBOGPydkhjB9BPx/Ql2WBQKP4swZwO5KyroMjJ67ONtpfU3dhX0tEwvKhjZFwbdFZ/enS7j4qJBVkQLmA8Akm9zosuPkOY3F8gbtyvc4pGRiFLmbydRugvP0S/7YU/7WTZlWBuKuOOSQq8K6nx3MvmoGuWqidR4XmYXMp/uA92bBOmxB2+OiN9BKpjrJ3X4H6UpnF7CxbdMQBbUwUaQOtJYWSIfDRMBrUmewKTrzzQ4KyRxgo0LV1ajFVMCwzBW6Y+xn2CpiDSqJc1rz+YY+Sn5surxr0PSgNWHuCgyGdJhaNCjILAsKNZayEN03PIWudzfXs4TH5bXsaxQJFkZixGek5LXa0R6lUl/FQWKPPqTsc9cWZ0rSa1aJxLyxnHSZGq/e2cDHt6uMkRbqlP+vfq1HnZlVtVe9LMRWZCwmLtlk/GOsjKWGVarhqO4P378Pm89Mz+TD6sZYH3VisPtMMlpSm24Zuckied3RnfD5WIoZ3eLxKrEPGrmK69EXJl04wLpHsFEgLdlapqdjZqFPSUrFJkNCcKUestxrhM6hRutPx4SMHvCH27OU="

notifications:
  email: false

sudo: false
